### ISSUE TITLE
Running action inside of container does not work

### ISSUE THREAD

**Issue by natlibfi-jonollil** [mikaelvesavuori/license-compliance-action#3]
```yaml
  license-scan:
    name: License compliance check
    runs-on: ubuntu-latest
    container: docker://node:20

    steps:
      - uses: actions/checkout@v4
      - uses: mikaelvesavuori/license-compliance-action@v1.0.2
```
My deduction is that location of script.sh file is not in same place as in the runner.
https://github.com/NatLibFi/melinda-ui-commons/actions/runs/7970133107/job/21757144607
